In [53]:
#importing all the necessary libraries
import pandas as pd
from sklearn import datasets
import numpy as np 

In [54]:
#mounting the google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [55]:
#importing the required dataframe
df = pd.read_csv('/content/drive/MyDrive/Regression Classification Final Exam/fixeddataset (1).csv')
df

Index   Age   Height   Weight   Income   Class
0        1    32      180       78    71500       1
1        2    28      165       58    25000       1
2        3    45      175       82    93500       2
3        4    35      170       65    62000       1
4        5    50      185       90    84000       1
..     ...   ...      ...      ...      ...     ...
195    196    28      161       57    27000       1
196    197    36      175       78    63000       1
197    198    30      163       59    20000       0
198    199    37      177       80    65000       1
199    200    29      165       58    22000       1

[200 rows x 6 columns]

In [56]:
#retrieving column names from the dataframe
print(df.columns)

Index(['Index', ' Age', ' Height', ' Weight', ' Income', ' Class'], dtype='object')


In [57]:
#printing data from column name to check if column name is attributed to the values in the column
print(df[' Class'])

0      1
1      1
2      2
3      1
4      1
      ..
195    1
196    1
197    0
198    1
199    1
Name:  Class, Length: 200, dtype: int64


In [58]:
#now, we assign the values in the ' Income' column to the feature_names array for use in SciKitLearn
income = ' Income'
#the income_data needs to be reshaped to be able to be used for fitting, because there is only one feature here
#therefore, the income_data array is in 1D format, but we need it in 2D format to be able to fit
#if we try and fit the model using income_data directly, there will be an error
income_data = df[income].values.reshape(-1, 1)
feature_names = [income]
print(feature_names)

[' Income']


In [59]:
print(income_data)

[[71500]
 [25000]
 [93500]
 [62000]
 [84000]
 [35000]
 [57500]
 [42500]
 [88000]
 [11000]
 [79000]
 [61000]
 [96000]
 [ 7000]
 [82000]
 [46000]
 [70000]
 [19000]
 [89000]
 [21000]
 [67000]
 [39000]
 [97000]
 [40000]
 [64000]
 [ 9000]
 [93000]
 [48000]
 [87000]
 [15000]
 [55000]
 [38000]
 [99000]
 [16000]
 [60000]
 [ 6000]
 [96000]
 [43000]
 [87000]
 [14000]
 [52000]
 [44000]
 [99000]
 [22000]
 [62000]
 [19000]
 [83000]
 [52000]
 [68000]
 [ 8000]
 [93000]
 [39000]
 [91000]
 [24000]
 [59000]
 [42000]
 [94000]
 [17000]
 [62000]
 [12000]
 [55000]
 [39000]
 [99000]
 [18000]
 [85000]
 [ 8000]
 [96000]
 [42000]
 [78000]
 [20000]
 [58000]
 [40000]
 [93000]
 [16000]
 [61000]
 [ 5000]
 [87000]
 [53000]
 [69000]
 [10000]
 [94000]
 [43000]
 [90000]
 [26000]
 [60000]
 [17000]
 [66000]
 [20000]
 [95000]
 [41000]
 [82000]
 [13000]
 [56000]
 [37000]
 [98000]
 [15000]
 [70000]
 [ 7000]
 [89000]
 [51000]
 [97000]
 [44000]
 [92000]
 [23000]
 [61000]
 [35000]
 [63000]
 [40000]
 [94000]
 [42000]
 [77000]
 

In [60]:
#now, we assign the values in the ' Class' column to the target array for use in SciKitLearn
income_class = ' Class'
income_class_data = df[income_class].values
target = income_class_data
print(target)

[1 1 2 1 1 1 1 1 1 0 1 1 2 0 1 1 1 0 1 1 1 1 2 1 1 0 2 1 1 0 1 1 2 0 1 0 2
 1 1 0 1 1 2 1 1 0 1 1 1 0 2 1 1 1 1 1 2 0 1 0 1 1 2 0 1 0 2 1 1 0 1 1 2 0
 1 0 1 1 1 0 2 1 1 1 1 0 1 0 2 1 1 0 1 1 2 0 1 0 1 1 2 1 1 1 1 1 1 1 2 1 1
 0 2 1 1 1 1 1 1 0 2 1 1 0 1 1 1 1 2 1 1 0 2 1 1 1 1 0 1 1 2 1 1 0 1 1 1 1
 2 1 1 0 2 1 1 1 1 0 1 1 2 1 1 0 1 1 1 1 2 1 1 0 2 1 1 1 1 0 1 1 2 1 1 0 1
 1 1 1 2 1 1 0 2 1 1 1 1 0 1 1]


In [61]:
#the next step is to map target_names to 0, 1 and 2
#here, 0 corresponds to 'Lower Class', 1 corresponds to 'Middle Class' and 2 corresponds to 'Upper Class'
#we do this so that SciKitLearn can read target names

# Define the target mapping
target_mapping = {0: 'Lower Class', 1: 'Middle Class', 2: 'Upper Class'}

# Map target values to target names
target_names = [target_mapping[value] for value in target]

# Print the target names
print(target_names)

['Middle Class', 'Middle Class', 'Upper Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Lower Class', 'Middle Class', 'Middle Class', 'Upper Class', 'Lower Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Lower Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Upper Class', 'Middle Class', 'Middle Class', 'Lower Class', 'Upper Class', 'Middle Class', 'Middle Class', 'Lower Class', 'Middle Class', 'Middle Class', 'Upper Class', 'Lower Class', 'Middle Class', 'Lower Class', 'Upper Class', 'Middle Class', 'Middle Class', 'Lower Class', 'Middle Class', 'Middle Class', 'Upper Class', 'Middle Class', 'Middle Class', 'Lower Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Lower Class', 'Upper Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Middle Class', 'Upper Class', 'Lower Class', 'Middle Class', 'Lower Class', 'Middle Class', 'Middle Class', 'Upper Class', 'Lower Class'

In [62]:
#now, we know the target names have been correctly mapped to the numbers 
#we'll use the variables 'income_data' and 'target' to begin fitting
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3, metric='minkowski',p=2)
knn.fit(income_data, target)

KNeighborsClassifier(n_neighbors=3)

In [63]:
#the model has been fitted to accept an income value and make a prediction on the class
#therefore, we now test to check if the ML model works
x_new = np.array([92000])
knn.predict([x_new])

array([2])

In [64]:
#the value 2 corresponds to Upper class
#now, we make a train/test split for our data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(income_data, target, test_size=0.2,stratify= target)
x_train.shape

(160, 1)

In [65]:
#now we know the training/testing split (160 entries for train, 40 entries for test, 80/20 split)
#we now fit the model to the training data and ask the model to predict on the test data
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)
y_predict = knn.predict(x_test)
y_predict

array([0, 1, 2, 1, 1, 2, 2, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 2, 0, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [66]:
#finally, we test the model for accuracy.
knn.score(x_test, y_test)

0.975